### ISSUE TITLE
is it possible that the email to send is not a constant?

### ISSUE THREAD

**Issue by cezar-pereira** [xreef/EMailSender#13]
is it possible that the email to send is not a constant? I need email to be dynamic, for example, promoting firebase.

**Comment by svdrummer** [comment]
Will be abused for spam.

**Comment by xreef** [comment]
Hi,
sorry but I don't understand, continue to the forum https://www.mischianti.org/forums/topic/is-it-possible-that-the-email-to-send-is-not-a-constant/ .
Thanks Renzo
