### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by gabrielestentella** [xreef/EMailSender#16]
I've uploaded the  code on my esp8266 module, but it doesn't send any email, moreover i can se only this output on the serial monitor:

ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld

how can I solve?

**Comment by xreef** [comment]
Hi,
what code did you upload and which esp8266 did you use?
Bye Renzo

**Comment by gabrielestentella** [comment]
I've just solved, thank you
