### ISSUE TITLE
send csv file but failed

### ISSUE THREAD

**Issue by FehnrirX** [xreef/EMailSender#17]
please help.

i want to send csv file from spiffs with this path

String fileName = todayDate + ".csv";
String path = "/Data Absensi/" + todayDate + ".csv";

so i will send different csv every day, but it keep giving me error when i compile it

    EMailSender::FileDescriptior fileDescriptor[1];
    fileDescriptor[0].filename = F(fileName);
    fileDescriptor[0].url = F(path);
    fileDescriptor[0].storageType = EMailSender::EMAIL_STORAGE_TYPE_SPIFFS;
    fileDescriptor[0].mime = MIME_TEXT_PLAIN;

error is

In file included from C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/Arduino.h:286,
                 from C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/FS.h:25,
                 from D:\Project\Arduino\curt2\webserver_email\webserver_email.ino:2:
D:\Project\Arduino\curt2\webserver_email\webserver_email.ino: In function 'void sendToEmail()':
webserver_email:612:36: error: initializer fails to determine size of '__pstr__'
  612 |     fileDescriptor[0].filename = F(fileName);
C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/WString.h:39:76: note: in definition of macro 'FPSTR'
   39 | #define FPSTR(pstr_pointer) (reinterpret_cast<const __FlashStringHelper *>(pstr_pointer))
      |                                                                            ^~~~~~~~~~~~
D:\Project\Arduino\curt2\webserver_email\webserver_email.ino:612:34: note: in expansion of macro 'F'
  612 |     fileDescriptor[0].filename = F(fileName);
      |                                  ^
webserver_email:612:36: error: array must be initialized with a brace-enclosed initializer
  612 |     fileDescriptor[0].filename = F(fileName);
C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/WString.h:39:76: note: in definition of macro 'FPSTR'
   39 | #define FPSTR(pstr_pointer) (reinterpret_cast<const __FlashStringHelper *>(pstr_pointer))
      |                                                                            ^~~~~~~~~~~~
D:\Project\Arduino\curt2\webserver_email\webserver_email.ino:612:34: note: in expansion of macro 'F'
  612 |     fileDescriptor[0].filename = F(fileName);
      |                                  ^
webserver_email:613:31: error: initializer fails to determine size of '__pstr__'
  613 |     fileDescriptor[0].url = F(path);
C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/WString.h:39:76: note: in definition of macro 'FPSTR'
   39 | #define FPSTR(pstr_pointer) (reinterpret_cast<const __FlashStringHelper *>(pstr_pointer))
      |                                                                            ^~~~~~~~~~~~
D:\Project\Arduino\curt2\webserver_email\webserver_email.ino:613:29: note: in expansion of macro 'F'
  613 |     fileDescriptor[0].url = F(path);
      |                             ^
webserver_email:613:31: error: array must be initialized with a brace-enclosed initializer
  613 |     fileDescriptor[0].url = F(path);
C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/WString.h:39:76: note: in definition of macro 'FPSTR'
   39 | #define FPSTR(pstr_pointer) (reinterpret_cast<const __FlashStringHelper *>(pstr_pointer))
      |                                                                            ^~~~~~~~~~~~
D:\Project\Arduino\curt2\webserver_email\webserver_email.ino:613:29: note: in expansion of macro 'F'
  613 |     fileDescriptor[0].url = F(path);
      |                             ^
Multiple libraries were found for "SD.h"
 Used: C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
exit status 1
initializer fails to determine size of '__pstr__'

what should i do?

**Comment by xreef** [comment]
Hi FehnrirX,
you must remove F.
Bye Renzo

**Comment by FehnrirX** [comment]
Hi Renzo

Thanks for the respond. but now i get new issue

  fileDescriptor[0].filename = fileName;
  fileDescriptor[0].url = path;

already check the contain of path and fileName, but serial show like this

![Serial port read](https://user-images.githubusercontent.com/82654724/123403370-e8c4eb80-d5d2-11eb-9e49-bbb5b9cd2a3e.png)

any suggestion?

**Comment by xreef** [comment]
Hi FehnrirX,
SPIFFS have some limitation (and directories were emulated not real), I think you don't use filename compliant.
Try to open It on a simple sketch.
You can find [information here](https://www.mischianti.org/2019/08/30/wemos-d1-mini-esp8266-integrated-spiffs-filesistem-part-2/).

Bye Renzo

**Comment by FehnrirX** [comment]
![image](https://user-images.githubusercontent.com/82654724/123426934-31d66900-d5ee-11eb-96ce-a36a3897b2d1.png)

here's what it looks like. already match with the contain of the path

**Comment by xreef** [comment]
Hi,
put the complete code on the forum and I'm going to debug.
https://www.mischianti.org/forums/forum/yours-project/

Bye Renzo

**Comment by FehnrirX** [comment]
i did submit it but keeps giving me this error

![image](https://user-images.githubusercontent.com/82654724/123532564-65250f00-d738-11eb-87db-672946934bef.png)

may i send to your email perhaps?

**Comment by xreef** [comment]
[Solution found here.](https://www.mischianti.org/forums/topic/sending-via-email-csv-from-spiffs-daily-no-file-found/)
