### ISSUE TITLE
"Unsecure App"?

### ISSUE THREAD

**Issue by cezar-pereira** [xreef/EMailSender#18]
Hi, I have a question, is there any way to not have to activate the "Unsecure App"?, because if I activate this option, google will automatically deactivate it if it is not used.

My question is if it's possible to prevent google from disabling "App not secure" or if there's another way I don't need to enable it.

**Comment by xreef** [comment]
Hi,
you can create an application password.
Look here.
https://www.mischianti.org/2020/06/16/send-email-with-attachments-emailsender-v2-x-library-esp32-and-esp8266-part-2/#Create_an_application_password
Bye Renzo

**Comment by cezar-pereira** [comment]
Gratitude!!! Very good.
