### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by DerDoubleD** [xreef/EMailSender#19]
Thanks for great work
I get warnings. See below...

In file included from src/test.cpp:275:0:
.pio/libdeps/az-delivery-devkit-v4/EMailSender/EMailSender.h:222:0: warning: "EMAIL_NETWORK_CLASS" redefined
 #define EMAIL_NETWORK_CLASS EMAIL_NETWORK_SSL_CLASS
 ^
In file included from src/test.cpp:275:0:
.pio/libdeps/az-delivery-devkit-v4/EMailSender/EMailSender.h:165:0: note: this is the location of the previous definition
 #define EMAIL_NETWORK_CLASS WiFiClient
 ^

best regards

**Comment by xreef** [comment]
Hi, 
Yes it's true. I redefine the define to simplify configuration.
Thanks Renzo
