### ISSUE TITLE
EMailSenderEsp32GMailLITTLEFSAttachTest.ino

### ISSUE THREAD

**Issue by froussel** [xreef/EMailSender#21]
Hello,

With ESP32 -S2   wemos S2 mini and
EMailSenderEsp32GMailLITTLEFSAttachTest.ino

With 
fileDescriptor[0].storageType = EMailSender::EMAIL_STORAGE_TYPE_LITTLEFS;

'EMAIL_STORAGE_TYPE_LITTLEFS' is not a member of 'EMailSender'

But with
 fileDescriptor[0].storageType = EMailSender::EMAIL_STORAGE_TYPE_LITTLE_FS;

In file included from C:\Users\admin\Desktop\arduino-1.8.18\portable\sketchbook\__sources\esp32 s2\EMailSenderEsp32GMailLITTLEFSAttachTest\EMailSenderEsp32GMailLITTLEFSAttachTest.ino:15:
C:\Users\admin\Desktop\arduino-1.8.18\portable\sketchbook\libraries\EMailSender/EMailSender.h:222: warning: "EMAIL_NETWORK_CLASS" redefined
 #define EMAIL_NETWORK_CLASS EMAIL_NETWORK_SSL_CLASS
 
In file included from C:\Users\admin\Desktop\arduino-1.8.18\portable\sketchbook\__sources\esp32 s2\EMailSenderEsp32GMailLITTLEFSAttachTest\EMailSenderEsp32GMailLITTLEFSAttachTest.ino:15:
C:\Users\admin\Desktop\arduino-1.8.18\portable\sketchbook\libraries\EMailSender/EMailSender.h:165: note: this is the location of the previous definition
 #define EMAIL_NETWORK_CLASS WiFiClient
 
C:\Users\admin\Desktop\arduino-1.8.18\portable\sketchbook\libraries\LittleFS_esp32\src\LITTLEFS.cpp: In member function 'virtual bool LITTLEFSImpl::exists(const char*)':
C:\Users\admin\Desktop\arduino-1.8.18\portable\sketchbook\libraries\LittleFS_esp32\src\LITTLEFS.cpp:44:28: error: no matching function for call to 'LITTLEFSImpl::open(const char*&, const char [2])'
     File f = open(path, "r");
                            ^
In file included from C:\Users\admin\Desktop\arduino-1.8.18\portable\sketchbook\libraries\LittleFS_esp32\src\LITTLEFS.cpp:17:
C:\Users\admin\Desktop\arduino-1.8.18\portable\packages\esp32\hardware\esp32\2.0.2\libraries\FS\src/vfs_api.h:38:17: note: candidate: 'virtual fs::FileImplPtr VFSImpl::open(const char*, const char*, bool)'
     FileImplPtr open(const char* path, const char* mode, const bool create) override;
                 ^~~~
C:\Users\admin\Desktop\arduino-1.8.18\portable\packages\esp32\hardware\esp32\2.0.2\libraries\FS\src/vfs_api.h:38:17: note:   candidate expects 3 arguments, 2 provided
Plusieurs bibliothèque trouvées pour "SD.h"
Utilisé : C:\Users\admin\Desktop\arduino-1.8.18\portable\packages\esp32\hardware\esp32\2.0.2\libraries\SD
Non utilisé : C:\Users\admin\Desktop\arduino-1.8.18\portable\sketchbook\libraries\SD
Plusieurs bibliothèque trouvées pour "WiFi.h"
Utilisé : C:\Users\admin\Desktop\arduino-1.8.18\portable\packages\esp32\hardware\esp32\2.0.2\libraries\WiFi
Non utilisé : C:\Users\admin\Desktop\arduino-1.8.18\portable\sketchbook\libraries\WiFi
exit status 1
Erreur de compilation pour la carte ESP32S2 Dev Module

Happy new year

fr

**Comment by xreef** [comment]
Hi fr,
thanks, I'm going to check as soon as possible.
Bye Renzo

**Comment by xreef** [comment]
Thanks
