### ISSUE TITLE
Particle.io Argon Support

### ISSUE THREAD

**Issue by ahartquist** [xreef/EMailSender#23]
Hello,

I was wondering what it would take to get this to work on a Particle Argon? 

I think I'm having a problem configuring the EMAIL_NETWORK_TYPE correctly, do you have any suggestions?

The Particle Argon uses a Espressif ESP32-D0WD 2.4 GHz Wi-Fi coprocessor. 

Best,

Alan

**Comment by xreef** [comment]
Hi @ahartquist,
I am asking for a sample device to integrate into my library.
Bye Renzo

**Comment by xreef** [comment]
Hi @ahartquist,
No response from particle, you can try to write yourself to help me be supported.
Bye Renzo
