### ISSUE TITLE
MKR ETH Shield support

### ISSUE THREAD

**Issue by jeromekasparian** [xreef/EMailSender#24]
Looks like SAMD Arduinos are only supported when using WifiNIMA. Support of Arduino MKR with MKR Eth Shield would be welcome.

**Comment by xreef** [comment]
Hi @jeromekasparian,
Ethernet is supported, you must set the correct value on SAMD space.

At this line https://github.com/xreef/EMailSender/blob/master/EMailSenderKey.h#L73

you must put 
`	#define DEFAULT_EMAIL_NETWORK_TYPE_SAMD 	NETWORK_W5100 `

I must release the most comprehensive version.

Bye Renzo
