### ISSUE TITLE
Could not connect to mail server, even if it's connecting.

### ISSUE THREAD

**Issue by mmbaguette** [xreef/EMailSender#25]
```cpp
EMailSender emailSend(email_login, email_pass, email_login, "smtp-mail.outlook.com", 587);
EMailSender::EMailMessage message;
message.subject = "Someone's home";
message.message = "I am!";
EMailSender::Response resp = emailSend.send("someemail@gmail.com", message);
Serial.println("Sending status: ");
Serial.println(resp.code);
Serial.println(resp.desc);
Serial.println(resp.status);
```
Result:
```
Sending status: 
2
Could not connect to mail server
0
```
My program will not connect to the Outlook SMTP mail servers, at least that's what it says.
However, I can see in Wireshark that it is communicating:
![image](https://user-images.githubusercontent.com/76597978/171773744-3aad7452-e696-462b-8412-31f266c58959.png)

It's just back and forth of the ESP sending line data and the server responding with the same 220 code.
![image](https://user-images.githubusercontent.com/76597978/171773845-f796ec16-d9aa-4e54-bf37-34c60ae8928e.png)

**Comment by xreef** [comment]
Hi @mmbaguette,
the library does not support TLS, sorry.
Bye Renzo
