### ISSUE TITLE
Work with Portenta H7 and Exchange Server

### ISSUE THREAD

**Issue by salasidis** [xreef/EMailSender#27]
I managed to get this to work as per the thread on the arduino forum

https://forum.arduino.cc/t/send-email-via-smtp-with-portenta/1006604/8

The main changes that were required were removing the colon from the end of the HELO command (I had changed it to EHLO via the function call).

``
String helo = commandHELO + " "String(publicIPDescriptor)";   <--- eliminating the colon at the end of this
``

I also had to increase the number of iterations to check for 
``
if (this->useEHLO == true) {
for (int i = 0; i<=11; i++) awaitSMTPResponse(client);
}
``

However, on this one it is likely better to add a larger number and stop the loop when the first call to the routine takes longer than say 1 second (ie no more left)

**Comment by xreef** [comment]
Hi @salasidis,
thanks for the tips.
TSL for the majority of devices doesn't work but It's good.
Using timeout can raise the execution time a lot.
I'm going to check the fix, but I think the ":" It's a misprint.
Bye Renzo

**Comment by xreef** [comment]
Less secure app no more work, you must create an application password.
Bye Renzo
