### ISSUE TITLE
Envoi de données dans le corps du mail

### ISSUE THREAD

**Issue by pg68390** [xreef/EMailSender#28]
Bonjour, tout d'abord merci pour le travail accompli sur ce code qui fonctionne très bien chez moi. Je poste car je voudrais pouvoir avec ce sketch envoyer des données par mail, c'est à dire dans le corps du mail ou même dans l'entête, je ne sais pas comment faire, quelqu'un peut il m'aider ? cordialement Phil

**Comment by xreef** [comment]
Hi, 
you can find all information on the site
https://www.mischianti.org/category/my-libraries/emailsender-send-email-with-attachments/
Bye Renzo

**Comment by xreef** [comment]
HI,
you can put on message everything, and you can use HTML tag also. So add the value of your variable to the message body and send It.
Bye Renzo

**Comment by pg68390** [comment]
@xreef Merci de me répondre si rapidement même en période de vacances, pouvez vous me donner un exemple de ligne de code avec une variable dans le corps du mail ?, merci je suis débutant et ne programme pas beaucoup, merci d'avance....
