### ISSUE TITLE
timeout with ESP32 and ethernet2

### ISSUE THREAD

**Issue by azadeh861367** [xreef/EMailSender#32]
I have tried the ESP32Gmailtest and worked ok with wifi. But I need to send Email through wired LAN. since I have used W5500 in my hardware, I changed these parameters in EmailSendKey.h:

#define DEFAULT_EMAIL_NETWORK_TYPE_ESP32 	NETWORK_ETHERNET_2  //NETWORK_ESP32
#define FORCE_DISABLE_SSL 

in setup routin, instead of wifi initialize, I have initialized Ethernet as follow:

Ethernet.init(5);
Ethernet.begin(mac, ip, mydns, mygw); 

after build and programming the result is:
Sending status: 
0
1
Connection Error! SMTP Response TIMEOUT!

could any body help me what additional changes should I make to send Email without Timeout error?
thanks in advance

**Comment by azadeh861367** [comment]
I forgot to mention that Sending a text is enough for me and I have also disabled ENABLE_ATTACHMENTS

**Comment by xreef** [comment]
Hi @azadeh861367,
Gmail can't work with w5500 without SSL, so first of all, you can't enable #define FORCE_DISABLE_SSL.
And you must use the last features of EMailSender library 
https://github.com/xreef/EMailSender/blob/master/EMailSenderKey.h#L77

`
#define SSLCLIENT_WRAPPER
`

by default, I add the GMail certificate, so It works without regenerating the thrust anchor, I must publish the documentation of this part.
Bye Renzo

**Comment by xreef** [comment]
Mmmmh, I'm not sure that Ethernet2 is compatible with SSLClient, I think you must switch to EthernetLarge (Ethernet with bigger buffer), but you can get more information here
https://www.mischianti.org/2022/07/13/stm32-ethernet-w5500-with-plain-http-and-ssl-https/#SSLClient_with_Ethernet
.
Bye Renzo
