### ISSUE TITLE
Raspberry Pi Pico W

### ISSUE THREAD

**Issue by chetan1836** [xreef/EMailSender#33]
I'm trying to send email from Pico W using this library. But, it is not working. What changes I've to make in order to work. Thanks.

**Comment by xreef** [comment]
Hi chetan,
what is the issue? And what do you do to put on working?
Bye Renzo

**Comment by chetan1836** [comment]
This is the response I'll get.
`Sending status: `
`0`
`2`
`Could not connect to mail server`

**Comment by xreef** [comment]
Hi chetan,
I can't help you if you don't explain what you are doing.
Bye Renzo

**Comment by chetan1836** [comment]
I'm trying to send email using Raspberry Pi Pico W and EmailSender library.

**Comment by xreef** [comment]
I test It repeatedly, and It works.
Bye Renzo
