### ISSUE TITLE
SMS Message Body displays as attachment

### ISSUE THREAD

**Issue by HeyBill55** [xreef/EMailSender#38]
When sending messages via ESP32 utilizing SMS email Scheme sourced from gmail account, the received message displays the subject correctly as text, but the body shows as an attachment.  Happens regardless of the mime type used.
[Attachment.txt](https://github.com/xreef/EMailSender/files/10921789/Attachment.txt)

**Comment by HeyBill55** [comment]
Additional Information:  Not sure if it's carrier specific issue.  Currently using T-Mobile.

**Comment by xreef** [comment]
Hi,
It's strange, I think the sms service read the encoding like a message.
Not now, but if I find some additional time I check It.
Bye Renzo

**Comment by HeyBill55** [comment]
Thanks Renzo!  Will be curious to know what you find out. BillSent from my iPhoneOn Mar 14, 2023, at 5:58 AM, Renzo Mischianti ***@***.***> wrote:﻿
Hi,
It's strange, I think the sms service read the encoding like a message.
Not now, but if I find some additional time I check It.
Bye Renzo

**Comment by radiohound** [comment]
I had the same issue, but if I edited the library EmailSender.h line 395 to String mime = "text/plain"; and it solved my issue. I am using myphonenumber@msg.fi.google.com (google fi) and a Raspberry Pico W. What is the correct way to fix this? I tried putting #define MIME_TEXT_PLAIN F("text/plain") in my arduino code, but that didn't help. Had to hard code it into the library as shown above.
