### ISSUE TITLE
Compilation error inside EMailSender.h:272:28

### ISSUE THREAD

**Issue by jaggil** [xreef/EMailSender#40]
Hello,
The following error occurs when compiling the library:
In file included from E:\Mis documentos\Arduino\libraries\EMailSender-master\EMailSender.cpp:35:
E:\Mis documentos\Arduino\libraries\EMailSender-master\EMailSender.cpp: In member function 'EMailSender::Response 
EMailSender::send(const char**, byte, byte, byte, EMailSender::EMailMessage&, EMailSender::Attachments)':
E:\Mis documentos\Arduino\libraries\EMailSender-master\EMailSender.h:272:28: error: invalid conversion from 'char' to 'const char*' [-fpermissive]
    #define EMAIL_FILE_READ 'r'

The correction is: #define EMAIL_FILE_READ "r"

Please, could you correct the master?
Greetings

**Comment by xreef** [comment]
Hi jaggil,
Please add microcontroller, framework version and configuration.
Bye Renzo
