### ISSUE TITLE
JSON link for auto install the library

### ISSUE THREAD

**Issue by xiaolaba** [xreef/EMailSender#6]
hi, very nice project.

Is it able to giving the json link for auto library installation with Arduino ? 

we could fork and json, but every of your update of pull request would have to pointing back to this master tree.

**Comment by xreef** [comment]
Hi Xiaolaba,
i can't find how to do It, I know that if you want add a library on library manager of Arduino IDE you must present a request here

https://github.com/arduino/Arduino/issues

but I try to find another solution if there is a method to do that without present subscription.

Bye Renzo

**Comment by xreef** [comment]
I try to do the request, vote It 

https://github.com/arduino/Arduino/issues/10505

Bye Renzo

**Comment by xiaolaba** [comment]
hello Renzo.

thx for the reply. It is likely the way to add library by the official support, and more there is another way to make "private resipotry" open wide and easy for user installation and auto updated once you have push an update version. I had learned that one time, a bit trivial but it is capable, feel free to try https://github.com/xiaolaba/picoCore

in case you are instresting to try one by yourself, would be my pleasure to tell some detail learned from other pinoneers.

**Comment by xreef** [comment]
Hi Xiaolaba,
I think that system is only for boards, not for library, Isn't Is?
Thanks Renzo

**Comment by xiaolaba** [comment]
hi Renzo, I did not fork/build for any library before, I would try to fork this one and tell the result if you do not mind. thx

**Comment by xreef** [comment]
Closed for inactivity.
