### ISSUE TITLE
Username and password encryption

### ISSUE THREAD

**Issue by Techknowdude** [xreef/EMailSender#8]
Thank you for an excellent plugin that worked first try without issues. There is one large issue though.

There does not seem to be support for any encryption that I can see for usernames or passwords.

Anything to protect public repos information would be greatly appreciated.

**Comment by xreef** [comment]
Hi Techknowdude,
I think that crypting can be applied by external program, 
the code when upload is compiled so you can't read the login e passwd on the code, 
but if you use some configuration file, you must apply the crypt there, and before set to library decode It.
Bye Renzo
