### ISSUE TITLE
Send user in mail

### ISSUE THREAD

**Issue by FrenchUser78** [xreef/EMailSender#9]
Hello,
I want to know if i can send a "user name" in a gmail mail with EmailSender.
I meen, when i receive the email, the sender name is xxx@gmail.com and i want it to be MYNAME for exemple.

I write
EMailSender emailSend("xxx@gmail.com", "pswd", "MYNAME", "smtp.gmail.com", 465);
and it s not working, the sender name is xxx@gmail.com

I try another library and it was possible..

Thanks

**Comment by xreef** [comment]
Hi FrenchUser78,
I add the features, and I'm going to describe It on the site documentation.
Bye Renzo
